### ISSUE TITLE
SwiftUI 徹底入門

### ISSUE THREAD

**Issue by watsonso** [mizuhiki-team/TIL#170]
- [ ] CHAPTER 01　SwiftUIの概要
- [ ] CHAPTER 02　SwiftUIのビューを理解する
- [ ] CHAPTER 03　レイアウトの作り方
- [ ] CHAPTER 04　状態の管理を委譲する
- [ ] CHAPTER 05　リストビューとスクロールビュー
- [ ] CHAPTER 06　図形の描画とカスタムビュー
- [ ] CHAPTER 07　ナビゲーション・シート・タブによる画面の切り替え
- [ ] CHAPTER 08　アラートとアクションシート
- [ ] CHAPTER 09　ビューアニメーションとエフェクト
- [ ] CHAPTER 10　状態とデータフロー
- [ ] CHAPTER 11　イベントとジェスチャ
- [ ] CHAPTER 12　フレームワーク統合とビューの作成
- [ ] CHAPTER 13　SwiftUIからCore Dataを使う
- [ ] CHAPTER 14　Advanced SwiftUI

**Comment by nhsykym** [comment]
同じの買ってるわ！目次いただきー！
